=== IvanPaharev97/task4/resources/treasures2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
		targetNamespace="http://www.epam.tc.com/treasures"
		xmlns:tns="http://www.epam.tc.com/treasures">
	<element name="treasures">
		<complexType>
			<sequence>
				<element name="treasure" type="tns:Treasure"
					minOccurs="0"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
	
	<complexType name="Treasure">
		<all>
			<element name="name" type="string" minOccurs="0" maxOccurs="1" />
			<element name="type" type="string" minOccurs="0" maxOccurs="1" />
			<element name="style" type="string" minOccurs="0" maxOccurs="1" />
			<element name="material" type="string" minOccurs="0" maxOccurs="1" />
			<element name="hardness" type="string" minOccurs="0" maxOccurs="1" />
			<element name="lockType" type="string" minOccurs="0" maxOccurs="1" />
			<element name="sandType" type="string" minOccurs="0" maxOccurs="1" />
			<element name="form" type="string" minOccurs="0" maxOccurs="1" />
			<element name="master" type="string" minOccurs="0" maxOccurs="1" />
			<element name="quality" type="string" minOccurs="0" maxOccurs="1" />
			<element name="paintType" type="string" minOccurs="0" maxOccurs="1" />
			<element name="whatOpen" type="string" minOccurs="0" maxOccurs="1" />
			<element name="tipType" type="string" minOccurs="0" maxOccurs="1" />
			<element name="handleType" type="string" minOccurs="0" maxOccurs="1" />
			<element name="bladeType" type="string" minOccurs="0" maxOccurs="1" />
			<element name="arrowType" type="string" minOccurs="0" maxOccurs="1" />
			<element name="language" type="string" minOccurs="0" maxOccurs="1" />
			<element name="content" type="string" minOccurs="0" maxOccurs="1" />
			<element name="magicSchool" type="string" minOccurs="0" maxOccurs="1" />
			<element name="magicWords" type="string" minOccurs="0" maxOccurs="1" />
			<element name="translation" type="string" minOccurs="0" maxOccurs="1" />
			<element name="accessory" type="string" minOccurs="0" maxOccurs="1" />
			<element name="dragonsKind" type="string" minOccurs="0" maxOccurs="1" />
			<element name="ornamentType" type="string" minOccurs="0" maxOccurs="1" />
			<element name="birthPlace" type="string" minOccurs="0" maxOccurs="1" />
			<element name="engravedRune" type="string" minOccurs="0" maxOccurs="1" />
			
			<element name="length" type="double" minOccurs="0" maxOccurs="1" />
			<element name="height" type="double" minOccurs="0" maxOccurs="1" />
			<element name="thickness" type="double" minOccurs="0" maxOccurs="1" />
			<element name="diameter" type="double" minOccurs="0" maxOccurs="1" />
			<element name="weight" type="double" minOccurs="0" maxOccurs="1" />
			<element name="capacity" type="double" minOccurs="0" maxOccurs="1" />
			<element name="price" type="double" minOccurs="0" maxOccurs="1" />
			<element name="girth" type="double" minOccurs="0" maxOccurs="1" />
			<element name="damage" type="double" minOccurs="0" maxOccurs="1" />
			<element name="headProtection" type="double" minOccurs="0" maxOccurs="1" />
			<element name="shoulderProtection" type="double" minOccurs="0" maxOccurs="1" />
			<element name="bodyProtection" type="double" minOccurs="0" maxOccurs="1" />
			<element name="legProtection" type="double" minOccurs="0" maxOccurs="1" />
			<element name="headGirth" type="double" minOccurs="0" maxOccurs="1" />
			<element name="shoulderGirth" type="double" minOccurs="0" maxOccurs="1" />
			<element name="bodyGirth" type="double" minOccurs="0" maxOccurs="1" />
			<element name="legGirth" type="double" minOccurs="0" maxOccurs="1" />
			<element name="age" type="double" minOccurs="0" maxOccurs="1" />
			
			<element name="arrowCount" type="int" minOccurs="0" maxOccurs="1" />
			<element name="pages" type="int" minOccurs="0" maxOccurs="1" />
			<element name="runesCapacity" type="int" minOccurs="0" maxOccurs="1" />
			<element name="count" type="int" minOccurs="0" maxOccurs="1" />
			
			<element name="hasLock" type="boolean" minOccurs="0" maxOccurs="1" />
			<element name="hasDamnation" type="boolean" minOccurs="0" maxOccurs="1" />
			<element name="hasPicture" type="boolean" minOccurs="0" maxOccurs="1" />
			<element name="hasOrnament" type="boolean" minOccurs="0" maxOccurs="1" />
			<element name="hasPreciousStone" type="boolean" minOccurs="0" maxOccurs="1" />
			
			<element name="creationDate" type="date" minOccurs="0" maxOccurs="1" />
			
			<element name="size" type="tns:Size" minOccurs="0" maxOccurs="1" />
		</all>
		<attribute name="id" type="int" use="required" />
		<attribute name="class" type="string" use="required" />
	</complexType>
	
	<complexType name="Size">
		<sequence>
			<element name="length" type="double" minOccurs="0" maxOccurs="1" />
			<element name="width" type="double" minOccurs="0" maxOccurs="1" />
			<element name="height" type="double" minOccurs="0" maxOccurs="1" />
		</sequence>
	</complexType>
	
</schema>

=== IvanPaharev97/task4/resources/treasures2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tc:treasures>
<tc:treasures xmlns:tc="http://www.epam.tc.com/treasures"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.epam.tc.com/treasures treasures2.xsd">


	<treasure id="1" class="">
	</treasure>
 	<treasure id="11" class="jewel">
		<type>Precious stone</type>
		<material>Diamond</material>
		<diameter>1.2</diameter>
		<weight>0.015</weight>
		<price>324.57</price>
	</treasure>
	<treasure id="12" class="jewel">
		<type>Precious stone</type>
		<material>Ruby</material>
		<diameter>5.1</diameter>
		<weight>0.51</weight>
		<price>117</price>
	</treasure>
	<treasure id="13" class="jewel">
		<type>Halfprecious stone</type>
		<material>Opal</material>
		<diameter>35.4</diameter>
		<weight>15.6</weight>
		<price>257.3</price>
	</treasure>

	<treasure id="21" class="ring">
		<material>Gold</material>
		<weight>2.7</weight>
		<style>Classic</style>
		<hasPreciousStone>true</hasPreciousStone>
		<price>751</price>
	</treasure>
	<treasure id="22" class="ring">
		<material>Platinum</material>
		<weight>6.1</weight>
		<style>Vintage</style>
		<hasPreciousStone>false</hasPreciousStone>
		<price>1024.33</price>
	</treasure>
	<treasure id="23" class="ring">
		<material>Silver</material>
		<weight>5.34</weight>
		<style>Vintage</style>
		<hasPreciousStone>false</hasPreciousStone>
		<price>99.99</price>
	</treasure>

	<treasure id="31" class="bracelet">
		<material>Silver</material>
		<weight>12.3</weight>
		<style>Classic</style>
		<bodyGirth>19.7</bodyGirth>
		<hardness>hard</hardness>
		<price>230.69</price>
	</treasure>
	<treasure id="32" class="bracelet">
		<material>Gold</material>
		<weight>13.1</weight>
		<style>Vintage</style>
		<bodyGirth>21.2</bodyGirth>
		<hardness>medium</hardness>
		<price>538.29</price>
	</treasure>
	<treasure id="33" class="bracelet">
		<material>Steel</material>
		<weight>11.9</weight>
		<style>Classic</style>
		<bodyGirth>20.2</bodyGirth>
		<hardness>hard</hardness>
		<price>214.99</price>
	</treasure>
	
	<treasure id="41" class="chain">
		<length>0.4</length>
		<weight>0.02</weight>
		<material>Gold</material>
		<thickness>0.01</thickness>
		<lockType>Sptreasure ring</lockType>
		<price>455</price>
	</treasure>
	<treasure id="42" class="chain">
		<length>0.35</length>
		<weight>0.016</weight>
		<material>Silver</material>
		<thickness>0.01</thickness>
		<lockType>Lobster</lockType>
		<price>130</price>
	</treasure>
	<treasure id="43" class="chain">
		<length>0.45</length>
		<weight>0.034</weight>
		<material>Gold</material>
		<thickness>0.014</thickness>
		<lockType>Barrel</lockType>
		<price>455</price>
	</treasure>

	<treasure id="51" class="sandglass">
		<material>Steel</material>
		<sandType>River sand</sandType>
		<weight>14</weight>
		<price>128</price>
	</treasure>
	<treasure id="52" class="sandglass">
		<material>Gold</material>
		<sandType>River sand</sandType>
		<weight>15.5</weight>
		<price>441</price>
	</treasure>
	<treasure id="53" class="sandglass">
		<material>Platinum</material>
		<sandType>Quarry sand</sandType>
		<weight>13</weight>
		<price>389</price>
	</treasure>
	
	<treasure id="61" class="beads">
		<length>0.35</length>
		<material>Amber</material>
		<weight>0.052</weight>
		<thickness>0.02</thickness>
		<price>205</price>
	</treasure>
	<treasure id="62" class="beads">
		<length>0.55</length>
		<material>Coral</material>
		<weight>0.110</weight>
		<thickness>0.03</thickness>
		<price>336</price>
	</treasure>
	<treasure id="63" class="beads">
		<length>0.40</length>
		<material>Emerald</material>
		<weight>0.210</weight>
		<thickness>0.03</thickness>
		<price>984</price>
	</treasure>
	
	<treasure id="71" class="coulomb">
		<material>gold</material>
		<size>
			<length>5</length>
			<width>3</width>
			<height>1</height>
		</size>
		<weight>40</weight>
		<form>square</form>
		<hasPicture>false</hasPicture>
		<price>140</price>
	</treasure>
	<treasure id="72" class="coulomb">
		<material>silver</material>
		<size>
			<length>2</length>
			<width>2</width>
			<height>0.5</height>
		</size>
		<weight>55</weight>
		<form>round</form>
		<hasPicture>true</hasPicture>
		<price>75</price>
	</treasure>
	<treasure id="73" class="coulomb">
		<material>bronze</material>
		<size>
			<length>5</length>
			<width>2</width>
			<height>0.7</height>
		</size>
		<weight>40</weight>
		<form>triangle</form>
		<hasPicture>true</hasPicture>
		<price>30</price>
	</treasure>

	<treasure id="81" class="cup">
		<capacity>650</capacity>
		<material>gold</material>
		<weight>150</weight>
		<height>70</height>
		<price>250</price>
	</treasure>
	<treasure id="82" class="cup">
		<capacity>250</capacity>
		<material>silver</material>
		<weight>25</weight>
		<height>45</height>
		<price>100</price>
	</treasure>
	<treasure id="83" class="cup">
		<capacity>375</capacity>
		<material>silver</material>
		<weight>50</weight>
		<height>50</height>
		<price>150</price>
	</treasure>
	
	<treasure id="91" class="vase">
		<name>Euphronios Krater</name>
		<type>Krater</type>
		<capacity>3</capacity>
		<hasPicture>true</hasPicture>
		<price>90</price>
	</treasure>
	<treasure id="92" class="vase">
		<name>Regina Vasorum</name>
		<type>Hydria</type>
		<capacity>5</capacity>
		<hasPicture>true</hasPicture>
		<price>60</price>
	</treasure>
	<treasure id="93" class="vase">
		<name>Ayla-Axum Amphorae</name>
		<type>Amphora</type>
		<capacity>4</capacity>
		<hasPicture>false</hasPicture>
		<price>75</price>
	</treasure>
	
	<treasure id="101" class="statue">
		<name>Petit Julien</name>
		<weight>50</weight>
		<size>
			<length>50</length>
			<width>20</width>
			<height>35</height>
		</size>
		<type>mannerism</type>
		<creationDate>1619-12-12</creationDate>
		<master>Jerome Duquesnoy l'Ancien</master>
		<price>1000</price>
	</treasure>
	<treasure id="102" class="statue">
		<name>Le Penseur</name>
		<weight>100</weight>
		<size>
			<length>80</length>
			<width>50</width>
			<height>150</height>
		</size>
		<type>realism</type>
		<creationDate>1882-04-02</creationDate>
		<master>Francois-Auguste-Rene Rodin</master>
		<price>200</price>
	</treasure>
	<treasure id="102" class="statue">
		<name>Le Denseur</name>
		<weight>80</weight>
		<size>
			<length>75</length>
			<width>65</width>
			<height>85</height>
		</size>
		<type>realism</type>
		<creationDate>1882-03-06</creationDate>
		<master>Rene Rodin-Marchenkovski</master>
		<price>200</price>
	</treasure>
	
	<treasure id="111" class="picture">
		<name>La Danse</name>
		<type>impressionism</type>
		<creationDate>1910-02-01</creationDate>
		<master>Henri Matisse</master>
		<quality>medium</quality>
		<paintType>oils</paintType>
		<price>3000</price>
	</treasure>
	<treasure id="112" class="picture">
		<name>Danse La</name>
		<type>barokko</type>
		<creationDate>1810-04-03</creationDate>
		<master>Henri Tisse</master>
		<quality>bad</quality>
		<paintType>gouache</paintType>
		<price>1000</price>
	</treasure>
	<treasure id="113" class="picture">
		<name>Danse La La</name>
		<type>marokko</type>
		<creationDate>1710-06-05</creationDate>
		<master>Henri Se</master>
		<quality>perfect</quality>
		<paintType>gouache</paintType>
		<price>30000</price>
	</treasure>
	
	<treasure id="121" class="casket">
		<size>
			<length>30</length>
			<width>20</width>
			<height>10</height>
		</size>
		<weight>1.2</weight>
		<hasLock>true</hasLock>
		<price>25</price>
	</treasure>
	<treasure id="122" class="casket">
		<size>
			<length>40</length>
			<width>40</width>
			<height>20</height>
		</size>
		<weight>1.8</weight>
		<hasLock>false</hasLock>
		<price>20</price>
	</treasure>
	<treasure id="123" class="casket">
		<size>
			<length>50</length>
			<width>35</width>
			<height>25</height>
		</size>
		<weight>2.5</weight>
		<hasLock>true</hasLock>
		<price>35</price>
	</treasure>
	
	<treasure id="131" class="key">
		<size>
			<length>5</length>
			<width>2</width>
			<height>1</height>
		</size>
		<type>English key</type>
		<whatOpen>casket</whatOpen>
		<price>10</price>
	</treasure>
	<treasure id="132" class="key">
		<size>
			<length>4</length>
			<width>0.8</width>
			<height>0.5</height>
		</size>
		<type>Socket wrench</type>
		<whatOpen>door</whatOpen>
		<price>12</price>
	</treasure>
	<treasure id="133" class="key">
		<size>
			<length>3</length>
			<width>0.5</width>
			<height>0.2</height>
		</size>
		<type>Perforated key</type>
		<whatOpen>lock</whatOpen>
		<price>15</price>
	</treasure>
	
	<treasure id="141" class="sword">
		<name>Katana</name>
		<material>steel</material>
		<weight>1.2</weight>
		<length>0.7</length>
		<type>curved</type>
		<thickness>0.004</thickness>
		<damage>130</damage>
		<price>212.4</price>
	</treasure>
	<treasure id="142" class="sword">
		<name>Jian</name>
		<material>steel</material>
		<weight>1.1</weight>
		<length>0.72</length>
		<type>straight</type>
		<thickness>0.003</thickness>
		<damage>110</damage>
		<price>191.1</price>
	</treasure>
	<treasure id="143" class="sword">
		<name>Golok</name>
		<material>steel</material>
		<weight>0.52</weight>
		<length>0.32</length>
		<type>machete</type>
		<thickness>0.005</thickness>
		<damage>43</damage>
		<price>98.5</price>
	</treasure>
	
	<treasure id="151" class="staff">
		<name>Bo</name>
		<length>1.8</length>
		<type>battle staff</type>
		<tipType>wood</tipType>
		<price>166.7</price>
	</treasure>
	<treasure id="152" class="staff">
		<name>Jo</name>
		<length>1.28</length>
		<type>battle staff</type>
		<tipType>wood</tipType>
		<price>111.5</price>
	</treasure>
	<treasure id="153" class="staff">
		<name>Kanabo</name>
		<length>1.41</length>
		<type>battle club</type>
		<tipType>steel</tipType>
		<price>177.5</price>
	</treasure>
	
	<treasure id = "161" class="mace">
		<name>Plastic</name>
		<type>simple</type>
		<size>
			<length>60</length>
			<width>15</width>
			<height>15</height>
		</size>
		<damage>30</damage>
		<price>50</price>
	</treasure>
	<treasure id = "162" class="mace">
		<name>Soldier</name>
