=== IvanPaharev97/task4/resources/treasures.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
		targetNamespace="http://www.epam.tc.com/treasures"
		xmlns:tns="http://www.epam.tc.com/treasures">
	<element name="treasures">
		<complexType>
			<sequence>
				<element name="treasure" type="tns:Treasure"
					minOccurs="0"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
		<unique name="uniqueID">
			<selector xpath=".//*" />
			<field xpath="@id" />
		</unique>
	</element>
	
	<complexType name="Treasure">
		<sequence>
			<element name="verbalProperty" type="tns:VerbalProperty" minOccurs="0" maxOccurs="unbounded" />
			<element name="doubleProperty" type="tns:DoubleProperty" minOccurs="0" maxOccurs="unbounded" />
			<element name="intProperty" type="tns:IntegerProperty" minOccurs="0" maxOccurs="unbounded" />
			<element name="hasProperty" type="tns:HasProperty" minOccurs="0" maxOccurs="unbounded" />
			<element name="dateProperty" type="tns:DateProperty" minOccurs="0" maxOccurs="unbounded" />
			<element name="price" type="decimal" minOccurs="0" maxOccurs="1"/>
		</sequence>
		<attribute name="id" type="int" use="required" />
		<attribute name="category" type="string" use="required" />
	</complexType>


	<complexType name="VerbalProperty">
		<sequence>
			<element name="value" type="string" />
		</sequence>
		<attribute name="name" type="string" use="required" />
	</complexType>
	
	<complexType name="IntegerProperty">
		<sequence>
			<element name="value" type="int" />
		</sequence>
		<attribute name="name" type="string" use="required" />
	</complexType>
	
	<complexType name="DoubleProperty">
		<sequence>
			<element name="value" type="double" />
		</sequence>
		<attribute name="name" type="string" use="required" />
	</complexType>
	
	<complexType name="HasProperty">
		<sequence>
			<element name="value" type="boolean" />
		</sequence>
		<attribute name="name" type="string" use="required" />
	</complexType>
	
	<complexType name="DateProperty">
		<sequence>
			<element name="value" type="date" />
		</sequence>
		<attribute name="name" type="string" use="required" />
	</complexType>
	
</schema>

=== IvanPaharev97/task4/resources/treasures.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tc:treasures>
<tc:treasures xmlns:tc="http://www.epam.tc.com/treasures"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.epam.tc.com/treasures treasures.xsd">

 	<treasure id="11" category="jewel">
 		<verbalProperty name="type">
 			<value>Precious stone</value>
 		</verbalProperty>
 		<verbalProperty name="material">
 			<value>Diamond</value>
 		</verbalProperty>
 		<doubleProperty name="diameter">
 			<value>1.2</value>
 		</doubleProperty>
 		<doubleProperty name="weight">
 			<value>0.015</value>
 		</doubleProperty>
		<price>324.57</price>
	</treasure>
	<treasure id="12" category="jewel">
		<verbalProperty name="type">
 			<value>Precious stone</value>
 		</verbalProperty>
 		<verbalProperty name="material">
 			<value>Ruby</value>
 		</verbalProperty>
 		 <doubleProperty name="diameter">
 			<value>5.1</value>
 		</doubleProperty>
 		<doubleProperty name="weight">
 			<value>0.51</value>
 		</doubleProperty>
		<price>117</price>
	</treasure>
	<treasure id="13" category="jewel">
		<verbalProperty name="type">
 			<value>Halfprecious stone</value>
 		</verbalProperty>
 		<verbalProperty name="material">
 			<value>Opal</value>
 		</verbalProperty>
 		<doubleProperty name="diameter">
 			<value>35.4</value>
 		</doubleProperty>
 		<doubleProperty name="weight">
 			<value>15.6</value>
 		</doubleProperty>
		<price>257.3</price>
	</treasure>

	<treasure id="21" category="ring">
		<verbalProperty name="material">
 			<value>Gold</value>
 		</verbalProperty>
 		<verbalProperty name="style">
 			<value>Classic</value>
 		</verbalProperty>
 		<doubleProperty name="weight">
 			<value>2.7</value>
 		</doubleProperty>
 		<hasProperty name="hasPreciousStone">
 			<value>true</value>
 		</hasProperty>
		<price>751</price>
	</treasure>
	<treasure id="22" category="ring">
		<verbalProperty name="material">
 			<value>Platinum</value>
 		</verbalProperty>
 		<verbalProperty name="style">
 			<value>Vintage</value>
 		</verbalProperty>
 		<doubleProperty name="weight">
 			<value>6.1</value>
 		</doubleProperty>
 		<hasProperty name="hasPreciousStone">
 			<value>false</value>
 		</hasProperty>
		<price>1024.33</price>
	</treasure>
	<treasure id="23" category="ring">
		<verbalProperty name="material">
 			<value>Silver</value>
 		</verbalProperty>
 		<verbalProperty name="style">
 			<value>Classic</value>
 		</verbalProperty>
 		<doubleProperty name="weight">
 			<value>5.34</value>
 		</doubleProperty>
 		<hasProperty name="hasPreciousStone">
 			<value>false</value>
 		</hasProperty>
		<price>99.99</price>
	</treasure>

	<treasure id="31" category="bracelet">
		<verbalProperty name="material">
 			<value>Silver</value>
 		</verbalProperty>
 		<verbalProperty name="style">
 			<value>Classic</value>
 		</verbalProperty>
 		<verbalProperty name="hardness">
 			<value>hard</value>
 		</verbalProperty>
 		<doubleProperty name="weight">
 			<value>12.3</value>
 		</doubleProperty>
 		<doubleProperty name="bodyGirth">
 			<value>19.7</value>
 		</doubleProperty>
		<price>230.69</price>
	</treasure>
	<treasure id="32" category="bracelet">
		<verbalProperty name="material">
 			<value>Gold</value>
 		</verbalProperty>
 		<verbalProperty name="style">
 			<value>Vintage</value>
 		</verbalProperty>
 		<verbalProperty name="hardness">
 			<value>medium</value>
 		</verbalProperty>
 		<doubleProperty name="weight">
 			<value>13.1</value>
 		</doubleProperty>
 		<doubleProperty name="bodyGirth">
 			<value>21.2</value>
 		</doubleProperty>
		<price>538.29</price>
	</treasure>
	<treasure id="33" category="bracelet">
		<verbalProperty name="material">
 			<value>Steel</value>
 		</verbalProperty>
 		<verbalProperty name="style">
 			<value>Classic</value>
 		</verbalProperty>
 		<verbalProperty name="hardness">
 			<value>hard</value>
 		</verbalProperty>
 		<doubleProperty name="weight">
 			<value>11.9</value>
 		</doubleProperty>
 		<doubleProperty name="bodyGirth">
 			<value>20.2</value>
 		</doubleProperty>
		<price>214.99</price>
	</treasure>
	
	<treasure id="41" category="chain">
		<verbalProperty name="material">
 			<value>Gold</value>
 		</verbalProperty>
 		<verbalProperty name="lockType">
 			<value>Sptreasure ring</value>
 		</verbalProperty>
 		<doubleProperty name="length">
 			<value>0.4</value>
 		</doubleProperty>
 		<doubleProperty name="weight">
 			<value>0.02</value>
 		</doubleProperty>
 		<doubleProperty name="thickness">
 			<value>0.01</value>
 		</doubleProperty>
		<price>455</price>
	</treasure>
	<treasure id="42" category="chain">
		<verbalProperty name="material">
 			<value>Silver</value>
 		</verbalProperty>
 		<verbalProperty name="lockType">
 			<value>Lobster</value>
 		</verbalProperty>
 		<doubleProperty name="length">
 			<value>0.35</value>
 		</doubleProperty>
 		<doubleProperty name="weight">
 			<value>0.016</value>
 		</doubleProperty>
 		<doubleProperty name="thickness">
 			<value>0.01</value>
 		</doubleProperty>
		<price>130</price>
	</treasure>
	<treasure id="43" category="chain">
		<verbalProperty name="material">
 			<value>Gold</value>
 		</verbalProperty>
 		<verbalProperty name="lockType">
 			<value>Barrel</value>
 		</verbalProperty>
 		<doubleProperty name="length">
 			<value>0.45</value>
 		</doubleProperty>
 		<doubleProperty name="weight">
 			<value>0.034</value>
 		</doubleProperty>
 		<doubleProperty name="thickness">
 			<value>0.014</value>
 		</doubleProperty>
		<price>455</price>
	</treasure>

	<treasure id="51" category="sandglass">
		<verbalProperty name="material">
 			<value>Steel</value>
 		</verbalProperty>
 		<verbalProperty name="sandType">
 			<value>Ground sand</value>
 		</verbalProperty>
 		<doubleProperty name="weight">
 			<value>14</value>
 		</doubleProperty>
		<price>128</price>
	</treasure>
	<treasure id="52" category="sandglass">
		<verbalProperty name="material">
 			<value>Gold</value>
 		</verbalProperty>
 		<verbalProperty name="sandType">
 			<value>River sand</value>
 		</verbalProperty>
 		<doubleProperty name="weight">
 			<value>15.5</value>
 		</doubleProperty>
		<price>441</price>
	</treasure>
	<treasure id="53" category="sandglass">
		<verbalProperty name="material">
 			<value>Platinum</value>
 		</verbalProperty>
 		<verbalProperty name="sandType">
 			<value>Quarry sand</value>
 		</verbalProperty>
 		<doubleProperty name="weight">
 			<value>13</value>
 		</doubleProperty>
		<price>389</price>
	</treasure>
	
	<treasure id="61" category="beads">
		<verbalProperty name="material">
 			<value>Amber</value>
 		</verbalProperty>
 		<doubleProperty name="length">
 			<value>0.35</value>
 		</doubleProperty>
 		<doubleProperty name="weight">
 			<value>0.052</value>
 		</doubleProperty>
 		<doubleProperty name="thickness">
 			<value>0.02</value>
 		</doubleProperty>
		<price>205</price>
	</treasure>
	<treasure id="62" category="beads">
		<verbalProperty name="material">
 			<value>Coral</value>
 		</verbalProperty>
 		<doubleProperty name="length">
 			<value>0.55</value>
 		</doubleProperty>
 		<doubleProperty name="weight">
 			<value>0.11</value>
 		</doubleProperty>
 		<doubleProperty name="thickness">
 			<value>0.03</value>
 		</doubleProperty>
		<price>336</price>
	</treasure>
	<treasure id="63" category="beads">
		<verbalProperty name="material">
 			<value>Emerald</value>
 		</verbalProperty>
 		<doubleProperty name="length">
 			<value>0.4</value>
 		</doubleProperty>
 		<doubleProperty name="weight">
 			<value>0.21</value>
 		</doubleProperty>
 		<doubleProperty name="thickness">
 			<value>0.03</value>
 		</doubleProperty>
		<price>984</price>
	</treasure>
	
	<treasure id="71" category="coulomb">
		<verbalProperty name="material">
 			<value>Gold</value>
 		</verbalProperty>
 		<verbalProperty name="form">
 			<value>square</value>
 		</verbalProperty>
 		<doubleProperty name="length">
 			<value>5</value>
 		</doubleProperty>
 		<doubleProperty name="width">
 			<value>3</value>
 		</doubleProperty>
 		<doubleProperty name="height">
 			<value>1</value>
 		</doubleProperty>
 		<doubleProperty name="weight">
 			<value>40</value>
 		</doubleProperty>
 		<hasProperty name="hasPicture">
 			<value>false</value>
 		</hasProperty>
		<price>140</price>
	</treasure>
	<treasure id="72" category="coulomb">
		<verbalProperty name="material">
 			<value>Silver</value>
 		</verbalProperty>
 		<verbalProperty name="form">
 			<value>round</value>
 		</verbalProperty>
 		<doubleProperty name="length">
 			<value>2</value>
 		</doubleProperty>
 		<doubleProperty name="width">
 			<value>2</value>
 		</doubleProperty>
 		<doubleProperty name="height">
 			<value>0.5</value>
 		</doubleProperty>
 		<doubleProperty name="weight">
 			<value>55</value>
 		</doubleProperty>
 		<hasProperty name="hasPicture">
 			<value>true</value>
 		</hasProperty>
		<price>75</price>
	</treasure>
	
	<treasure id="73" category="coulomb">
		<verbalProperty name="material">
 			<value>Bronze</value>
 		</verbalProperty>
 		<verbalProperty name="form">
 			<value>triangle</value>
 		</verbalProperty>
 		<doubleProperty name="length">
 			<value>5</value>
 		</doubleProperty>
 		<doubleProperty name="width">
 			<value>2</value>
 		</doubleProperty>
 		<doubleProperty name="height">
 			<value>0.7</value>
 		</doubleProperty>
 		<doubleProperty name="weight">
 			<value>40</value>
 		</doubleProperty>
 		<hasProperty name="hasPicture">
 			<value>true</value>
 		</hasProperty>
		<price>30</price>
	</treasure>

	<treasure id="81" category="cup">
		<verbalProperty name="material">
 			<value>Gold</value>
 		</verbalProperty>
		<doubleProperty name="capacity">
 			<value>650</value>
 		</doubleProperty>
 		<doubleProperty name="height">
 			<value>70</value>
 		</doubleProperty>
 		<doubleProperty name="weight">
 			<value>150</value>
 		</doubleProperty>
		<price>250</price>
	</treasure>
	<treasure id="82" category="cup">
		<verbalProperty name="material">
